[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5000
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200